### ISSUE TITLE
Spacing is removed before and after inline links

### ISSUE THREAD

**Issue by mwhawkins** [xfenix/django-hmin#3]
The minification process seems to remove spaces before and after inline links leading to things like this

`Here is my filedownload it nowand it will be good`

Where "download it now" is a link with <a href=" ... etc.

**Comment by xfenix** [comment]
Thanks for bugreport.
I try to reproduce this and fix. It may be because i added more aggressive space stripping regex in the 2020 update.

**Comment by xfenix** [comment]
Yeap, it was bad regexp. I fixed fixtures and algorithms. I need to test more features and speed, it may took some time. So i just dont bump version yet. It will happen soon.

**Comment by xfenix** [comment]
https://github.com/xfenix/django-hmin/releases/tag/0.5.3 release 0.5.3 ready and published. Please, if you can, check it and write, if you got any issues.
Thanks for bug report, it helps a lot.
